package export

import (
	"errors"
	"fmt"
	"maps"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/matcra587/docent"
)

// generatedHeader is the static do-not-edit comment written at the top of
// every exported skill file. It is a package-level constant so the output is
// byte-stable — no timestamps, no version strings, no dynamic content.
const generatedHeader = "<!-- Code generated by docent; DO NOT EDIT. -->"

// Renderer is the interface implemented by all export formats. A Renderer
// converts a single Guide into its text representation and names the artifact
// path it belongs at; I/O is the caller's responsibility — Write is the
// package's own root-scoped implementation of that responsibility.
type Renderer interface {
	// Render returns the complete artifact text for g.
	Render(g docent.Guide) string

	// RelPath returns the artifact's path relative to the export root,
	// always in forward-slash form.
	RelPath(g docent.Guide) string
}

// ValidatingRenderer is a Renderer that validates a guide before Write
// creates the export directory. The built-in skill renderers implement it
// so a host-supplied name qualifier cannot produce a non-conformant skill.
// Host renderers may implement it when their own artifact contract has
// validation that must complete before any files are written.
type ValidatingRenderer interface {
	Renderer

	// Validate reports whether g can be rendered without violating the
	// renderer's artifact contract.
	Validate(g docent.Guide) error
}

// skillNamePattern is the Agent Skills name grammar: lowercase alphanumeric
// runs separated by single hyphens.
var skillNamePattern = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

// maxSkillNameLen is the Agent Skills name length cap in characters.
const maxSkillNameLen = 64

// AgentSkill renders a docent.Guide to the portable SKILL.md shape defined
// by the Agent Skills open standard (agentskills.io), the common format
// consumed by Claude Code, Codex, and other agent runtimes. The frontmatter
// carries exactly the spec's two required fields: name (the optionally
// qualified guide slug, which also names the artifact directory, satisfying
// the spec's name-matches-directory rule) and description (the guide
// description and when_to_use joined, so a harness can decide whether to load
// the skill without reading the runbook).
//
// Artifacts conform to the neutral spec and pass its reference validator
// (skills-ref); this is the format to reach for when the consuming harness
// is unknown.
//
// Output is deterministic and byte-stable for identical input.
type AgentSkill struct {
	// NameQualifier prefixes the source guide slug in the emitted skill name
	// and directory, separated by a hyphen. Empty preserves the source slug
	// and the historical byte shape. Write validates the final composed name
	// against the Agent Skills constraints before creating any files.
	NameQualifier string
}

// Compile-time assertion: AgentSkill must satisfy the ValidatingRenderer
// interface, which includes Renderer.
var _ ValidatingRenderer = (*AgentSkill)(nil)

// Render returns the open-standard SKILL.md text for g.
func (r AgentSkill) Render(g docent.Guide) string {
	fm := [][2]string{
		{"description", g.SkillDescription()},
	}

	return renderSkill(fm, g, r.skillName(g))
}

// RelPath returns the artifact path for g relative to the export root:
// <name>/SKILL.md, the directory-per-skill layout the spec requires.
func (r AgentSkill) RelPath(g docent.Guide) string {
	return skillRelPath(r.skillName(g))
}

// Validate reports whether the qualified name is a conformant Agent Skills
// name and matches the artifact's parent directory.
func (r AgentSkill) Validate(g docent.Guide) error {
	name := r.skillName(g)

	return validateSkillNameAndPath(name, r.RelPath(g))
}

// skillName returns the export-only name without mutating g.Slug.
func (r AgentSkill) skillName(g docent.Guide) string {
	return qualifiedSkillName(r.NameQualifier, g.Slug)
}

// ClaudeSkill renders a docent.Guide to the Claude Code variant of the
// SKILL.md shape. Claude Code extends the open standard with a native
// when_to_use frontmatter field — documented at
// https://code.claude.com/docs/en/skills.md as "appended to description in
// the skill listing" — so this renderer keeps description and when_to_use
// as separate keys instead of joining them. Everything else — layout, name
// rules, body — is identical to AgentSkill.
//
// Artifacts conform to Claude Code's documented schema, not the neutral
// spec: the neutral reference validator (skills-ref) rejects when_to_use by
// design, since the spec's own extension slot is the metadata map. Validate
// claude-skill output against Claude Code's field set; use AgentSkill when
// the consuming harness is unknown. Claude Code caps the combined
// description and when_to_use listing text at 1,536 characters; docent's
// load-time budget (MaxSkillDescription, 1024, from the neutral spec) is
// stricter, so a valid guide can never exceed it.
//
// Output is deterministic and byte-stable for identical input.
type ClaudeSkill struct {
	// NameQualifier prefixes the source guide slug in the emitted skill name
	// and directory, separated by a hyphen. Empty preserves the source slug
	// and the historical byte shape. Write validates the final composed name
	// against the Agent Skills constraints before creating any files.
	NameQualifier string
}

// Compile-time assertion: ClaudeSkill must satisfy the ValidatingRenderer
// interface, which includes Renderer.
var _ ValidatingRenderer = (*ClaudeSkill)(nil)

// Render returns the Claude Code SKILL.md text for g.
func (r ClaudeSkill) Render(g docent.Guide) string {
	fm := [][2]string{
		{"description", g.Description},
		{"when_to_use", g.WhenToUse},
	}

	return renderSkill(fm, g, r.skillName(g))
}

// RelPath returns the artifact path for g relative to the export root:
// <name>/SKILL.md, the directory-per-skill layout the spec requires.
func (r ClaudeSkill) RelPath(g docent.Guide) string {
	return skillRelPath(r.skillName(g))
}

// Validate reports whether the qualified name is a conformant Agent Skills
// name and matches the artifact's parent directory.
func (r ClaudeSkill) Validate(g docent.Guide) error {
	name := r.skillName(g)

	return validateSkillNameAndPath(name, r.RelPath(g))
}

// skillName returns the export-only name without mutating g.Slug.
func (r ClaudeSkill) skillName(g docent.Guide) string {
	return qualifiedSkillName(r.NameQualifier, g.Slug)
}

// qualifiedSkillName composes an export-only name. The empty branch is kept
// explicit so unqualified rendering remains byte-identical.
func qualifiedSkillName(qualifier, slug string) string {
	if qualifier == "" {
		return slug
	}

	return qualifier + "-" + slug
}

// skillRelPath is the one artifact layout every skill renderer shares:
// <name>/SKILL.md.
func skillRelPath(name string) string {
	return path.Join(name, "SKILL.md")
}

// validateSkillNameAndPath enforces the complete Agent Skills naming
// contract against the final exported name, including the requirement that
// frontmatter name match the SKILL.md parent directory.
func validateSkillNameAndPath(name, rel string) error {
	var errs []error

	if n := utf8.RuneCountInString(name); n == 0 || n > maxSkillNameLen {
		errs = append(errs, fmt.Errorf(
			"%w %q: length is %d characters; expected 1-%d",
			ErrInvalidSkillName,
			name,
			n,
			maxSkillNameLen,
		))
	}

	if !skillNamePattern.MatchString(name) {
		errs = append(errs, fmt.Errorf(
			"%w %q: expected lowercase alphanumerics and single hyphens with no leading or trailing hyphen",
			ErrInvalidSkillName,
			name,
		))
	}

	parent := path.Base(path.Dir(rel))
	if parent != name {
		errs = append(errs, fmt.Errorf(
			"%w %q: frontmatter name does not match parent directory %q",
			ErrInvalidSkillName,
			name,
			parent,
		))
	}

	return errors.Join(errs...)
}

// renderSkill writes the shared SKILL.md shape: the name field, the given
// frontmatter fields in order, the generated-do-not-edit header, then the
// guide body (title, description, when-to-use, and the six standard sections
// in validated order).
//
// The name is emitted as a plain scalar — its load-validated charset
// (lowercase alphanumerics and hyphens) can never need quoting, and quoting
// it would break naive parsers that compare the raw line against the
// directory name. Prose values are emitted as single-line double-quoted
// scalars rather than through a YAML marshaler: yaml.v3 folds long plain
// scalars across lines, which is valid YAML but breaks the line-oriented
// frontmatter parsers some harnesses use. strconv.Quote's escape forms
// (\", \\, \n, \t, \a, \v, \xHH, \uXXXX, \UXXXXXXXX) are all part of YAML's
// double-quoted style, so the output stays valid YAML with every value on
// one line. Guide content is valid UTF-8 by construction — the YAML parser
// rejected anything else at load — so the \xHH form is never reached with
// bytes a YAML reader would reinterpret.
func renderSkill(fm [][2]string, g docent.Guide, name string) string {
	var b strings.Builder

	b.WriteString("---\nname: ")
	b.WriteString(name)
	b.WriteString("\n")

	for _, kv := range fm {
		b.WriteString(kv[0])
		b.WriteString(": ")
		b.WriteString(strconv.Quote(kv[1]))
		b.WriteString("\n")
	}

	// Optional spec passthrough fields, shared by every skill format. Each
	// value stays a single-line quoted scalar (metadata one scalar per key,
	// keys sorted) so line-oriented frontmatter parsers keep working.
	if g.License != "" {
		b.WriteString("license: ")
		b.WriteString(strconv.Quote(g.License))
		b.WriteString("\n")
	}

	if g.Compatibility != "" {
		b.WriteString("compatibility: ")
		b.WriteString(strconv.Quote(g.Compatibility))
		b.WriteString("\n")
	}

	if len(g.AllowedTools) > 0 {
		// The spec defines allowed-tools as one space-separated string.
		b.WriteString("allowed-tools: ")
		b.WriteString(strconv.Quote(strings.Join(g.AllowedTools, " ")))
		b.WriteString("\n")
	}

	if len(g.Metadata) > 0 {
		b.WriteString("metadata:\n")

		for _, k := range slices.Sorted(maps.Keys(g.Metadata)) {
			// Keys are host-authored and may carry YAML-significant
			// characters; quoting them keeps the emitted frontmatter valid
			// YAML for any loadable guide, matching the value treatment.
			b.WriteString("  ")
			b.WriteString(strconv.Quote(k))
			b.WriteString(": ")
			b.WriteString(strconv.Quote(g.Metadata[k]))
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("\n\n# ")
	b.WriteString(g.Title)
	b.WriteString("\n\n")
	b.WriteString(g.Description)
	b.WriteString("\n\n## When to use\n\n")
	b.WriteString(g.WhenToUse)

	for _, s := range g.Sections {
		b.WriteString("\n\n## ")
		b.WriteString(s.Heading)
		b.WriteString("\n\n")
		b.WriteString(s.Body)
	}

	b.WriteString("\n")

	return b.String()
}
