package export

import (
	"maps"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/matcra587/docent"
)

// generatedHeader is the static do-not-edit comment written at the top of
// every exported skill file. It is a package-level constant so the output is
// byte-stable — no timestamps, no version strings, no dynamic content.
const generatedHeader = "<!-- Code generated by docent; DO NOT EDIT. -->"

// Renderer is the interface implemented by all export formats. A Renderer
// converts a single Guide into its text representation and names the artifact
// path it belongs at; I/O is the caller's responsibility.
type Renderer interface {
	// Render returns the complete artifact text for g.
	Render(g docent.Guide) string

	// RelPath returns the artifact's path relative to the export root,
	// always in forward-slash form.
	RelPath(g docent.Guide) string
}

// AgentSkill renders a docent.Guide to the portable SKILL.md shape defined
// by the Agent Skills open standard (agentskills.io), the common format
// consumed by Claude Code, Codex, and other agent runtimes. The frontmatter
// carries exactly the spec's two required fields: name (the guide slug,
// which also names the artifact directory, satisfying the spec's
// name-matches-directory rule) and description (the guide description and
// when_to_use joined, so a harness can decide whether to load the skill
// without reading the runbook).
//
// Artifacts conform to the neutral spec and pass its reference validator
// (skills-ref); this is the format to reach for when the consuming harness
// is unknown.
//
// Output is deterministic and byte-stable for identical input.
type AgentSkill struct{}

// Compile-time assertion: AgentSkill must satisfy the Renderer interface.
var _ Renderer = (*AgentSkill)(nil)

// Render returns the open-standard SKILL.md text for g.
func (AgentSkill) Render(g docent.Guide) string {
	fm := [][2]string{
		{"description", g.SkillDescription()},
	}

	return renderSkill(fm, g)
}

// RelPath returns the artifact path for g relative to the export root:
// <slug>/SKILL.md, the directory-per-skill layout the spec requires.
func (AgentSkill) RelPath(g docent.Guide) string {
	return skillRelPath(g)
}

// ClaudeSkill renders a docent.Guide to the Claude Code variant of the
// SKILL.md shape. Claude Code extends the open standard with a native
// when_to_use frontmatter field — documented at
// https://code.claude.com/docs/en/skills.md as "appended to description in
// the skill listing" — so this renderer keeps description and when_to_use
// as separate keys instead of joining them. Everything else — layout, name
// rules, body — is identical to AgentSkill.
//
// Artifacts conform to Claude Code's documented schema, not the neutral
// spec: the neutral reference validator (skills-ref) rejects when_to_use by
// design, since the spec's own extension slot is the metadata map. Validate
// claude-skill output against Claude Code's field set; use AgentSkill when
// the consuming harness is unknown. Claude Code caps the combined
// description and when_to_use listing text at 1,536 characters; docent's
// load-time budget (MaxSkillDescription, 1024, from the neutral spec) is
// stricter, so a valid guide can never exceed it.
//
// Output is deterministic and byte-stable for identical input.
type ClaudeSkill struct{}

// Compile-time assertion: ClaudeSkill must satisfy the Renderer interface.
var _ Renderer = (*ClaudeSkill)(nil)

// Render returns the Claude Code SKILL.md text for g.
func (ClaudeSkill) Render(g docent.Guide) string {
	fm := [][2]string{
		{"description", g.Description},
		{"when_to_use", g.WhenToUse},
	}

	return renderSkill(fm, g)
}

// RelPath returns the artifact path for g relative to the export root:
// <slug>/SKILL.md, the directory-per-skill layout the spec requires.
func (ClaudeSkill) RelPath(g docent.Guide) string {
	return skillRelPath(g)
}

// skillRelPath is the one artifact layout every skill renderer shares:
// <slug>/SKILL.md.
func skillRelPath(g docent.Guide) string {
	return path.Join(g.Slug, "SKILL.md")
}

// renderSkill writes the shared SKILL.md shape: the name field, the given
// frontmatter fields in order, the generated-do-not-edit header, then the
// guide body (title, description, when-to-use, and the six standard sections
// in validated order).
//
// The name is emitted as a plain scalar — its load-validated charset
// (lowercase alphanumerics and hyphens) can never need quoting, and quoting
// it would break naive parsers that compare the raw line against the
// directory name. Prose values are emitted as single-line double-quoted
// scalars rather than through a YAML marshaler: yaml.v3 folds long plain
// scalars across lines, which is valid YAML but breaks the line-oriented
// frontmatter parsers some harnesses use. strconv.Quote's escape forms
// (\", \\, \n, \t, \a, \v, \xHH, \uXXXX, \UXXXXXXXX) are all part of YAML's
// double-quoted style, so the output stays valid YAML with every value on
// one line. Guide content is valid UTF-8 by construction — the YAML parser
// rejected anything else at load — so the \xHH form is never reached with
// bytes a YAML reader would reinterpret.
func renderSkill(fm [][2]string, g docent.Guide) string {
	var b strings.Builder

	b.WriteString("---\nname: ")
	b.WriteString(g.Slug)
	b.WriteString("\n")

	for _, kv := range fm {
		b.WriteString(kv[0])
		b.WriteString(": ")
		b.WriteString(strconv.Quote(kv[1]))
		b.WriteString("\n")
	}

	// Optional spec passthrough fields, shared by every skill format. Each
	// value stays a single-line quoted scalar (metadata one scalar per key,
	// keys sorted) so line-oriented frontmatter parsers keep working.
	if g.License != "" {
		b.WriteString("license: ")
		b.WriteString(strconv.Quote(g.License))
		b.WriteString("\n")
	}

	if g.Compatibility != "" {
		b.WriteString("compatibility: ")
		b.WriteString(strconv.Quote(g.Compatibility))
		b.WriteString("\n")
	}

	if len(g.AllowedTools) > 0 {
		// The spec defines allowed-tools as one space-separated string.
		b.WriteString("allowed-tools: ")
		b.WriteString(strconv.Quote(strings.Join(g.AllowedTools, " ")))
		b.WriteString("\n")
	}

	if len(g.Metadata) > 0 {
		b.WriteString("metadata:\n")

		for _, k := range slices.Sorted(maps.Keys(g.Metadata)) {
			// Keys are host-authored and may carry YAML-significant
			// characters; quoting them keeps the emitted frontmatter valid
			// YAML for any loadable guide, matching the value treatment.
			b.WriteString("  ")
			b.WriteString(strconv.Quote(k))
			b.WriteString(": ")
			b.WriteString(strconv.Quote(g.Metadata[k]))
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("\n\n# ")
	b.WriteString(g.Title)
	b.WriteString("\n\n")
	b.WriteString(g.Description)
	b.WriteString("\n\n## When to use\n\n")
	b.WriteString(g.WhenToUse)

	for _, s := range g.Sections {
		b.WriteString("\n\n## ")
		b.WriteString(s.Heading)
		b.WriteString("\n\n")
		b.WriteString(s.Body)
	}

	b.WriteString("\n")

	return b.String()
}
